test for db generator error
ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for
servlet [dispatcherServlet] in context with path [] threw exception
[Request processing failed; nested exception is
org.springframework.transaction.TransactionSystemException: Could not
commit JPA transaction; nested exception is
javax.persistence.RollbackException: Error while committing the
transaction] with root cause
2020-10-20T08:25:55.721613+00:00 app[web.1]:
javax.validation.ConstraintViolationException: Validation failed for
classes [net.javaci.bank.db.model.Employee] during persist time for
groups [javax.validation.groups.Default, ]
2020-10-20T08:25:55.721614+00:00 app[web.1]: List of constraint
violations:[
2020-10-20T08:25:55.721615+00:00 app[web.1]:
ConstraintViolationImpl{interpolatedMessage='size must be between 1 and
10', propertyPath=lastName, rootBeanClass=class
net.javaci.bank.db.model.Employee,
messageTemplate='{javax.validation.constraints.Size.message}'}